SELECT E.*
FROM EMPLOYEES E
	LEFT JOIN ORDERS O
    ON E.EMPLOYEEID = O.EMPLOYEEID
    WHERE O.EMPLOYEEID IS NULL
;

-- SELECT *
-- FROM EMPLOYEES
-- WHERE EMPLOYEEID NOT IN (
--     SELECT DISTINCT EMPLOYEEID FROM ORDERS
-- )
-- ;