CREATE TABLE `MEMBER_INFO` (
	`MI_PK`	VARCHAR(20)	NOT NULL,
	`NAME`	VARCHAR(20)	NULL,
	`AGE`	INT	NULL,
	`GENDER`	VARCHAR(20)	NULL,
	`PHONE`	VARCHAR(20)	NULL,
	`EMAIL`	VARCHAR(300)	NULL
);

CREATE TABLE `MEMBER_HOBBY` (
	`MH_PK`	VARCHAR(20)	NOT NULL,
	`HOBBY`	VARCHAR(20)	NULL
);

CREATE TABLE `MEMBER_ADDRESS` (
	`MA_PK`	VARCHAR(20)	NOT NULL,
	`ADDRESS`	VARCHAR(300)	NULL
);

CREATE TABLE `MEMBER_INFO_HOBBY` (
	`MIH_PK`	VARCHAR(20)	NOT NULL,
	`MI_FK`	VARCHAR(20)	NOT NULL,
	`MH_FK`	VARCHAR(20)	NOT NULL
);

CREATE TABLE `MEMBER_INFO_ADDRESS` (
	`MIA_PK`	VARCHAR(20)	NOT NULL,
	`MI_FK`	VARCHAR(20)	NOT NULL,
	`MA_FK`	VARCHAR(20)	NOT NULL
);

ALTER TABLE `MEMBER_INFO` ADD CONSTRAINT `PK_MEMBER_INFO` PRIMARY KEY (
	`MI_PK`
);

ALTER TABLE `MEMBER_HOBBY` ADD CONSTRAINT `PK_MEMBER_HOBBY` PRIMARY KEY (
	`MH_PK`
);

ALTER TABLE `MEMBER_ADDRESS` ADD CONSTRAINT `PK_MEMBER_ADDRESS` PRIMARY KEY (
	`MA_PK`
);

ALTER TABLE `MEMBER_INFO_HOBBY` ADD CONSTRAINT `PK_MEMBER_INFO_HOBBY` PRIMARY KEY (
	`MIH_PK`,
	`MI_FK`,
	`MH_FK`
);

ALTER TABLE `MEMBER_INFO_ADDRESS` ADD CONSTRAINT `PK_MEMBER_INFO_ADDRESS` PRIMARY KEY (
	`MIA_PK`,
	`MI_FK`,
	`MA_FK`
);

ALTER TABLE `MEMBER_INFO_HOBBY` ADD CONSTRAINT `FK_MEMBER_INFO_TO_MEMBER_INFO_HOBBY_1` FOREIGN KEY (
	`MI_FK`
)
REFERENCES `MEMBER_INFO` (
	`MI_PK`
);

ALTER TABLE `MEMBER_INFO_HOBBY` ADD CONSTRAINT `FK_MEMBER_HOBBY_TO_MEMBER_INFO_HOBBY_1` FOREIGN KEY (
	`MH_FK`
)
REFERENCES `MEMBER_HOBBY` (
	`MH_PK`
);

ALTER TABLE `MEMBER_INFO_ADDRESS` ADD CONSTRAINT `FK_MEMBER_INFO_TO_MEMBER_INFO_ADDRESS_1` FOREIGN KEY (
	`MI_FK`
)
REFERENCES `MEMBER_INFO` (
	`MI_PK`
);

ALTER TABLE `MEMBER_INFO_ADDRESS` ADD CONSTRAINT `FK_MEMBER_ADDRESS_TO_MEMBER_INFO_ADDRESS_1` FOREIGN KEY (
	`MA_FK`
)
REFERENCES `MEMBER_ADDRESS` (
	`MA_PK`
);