CREATE TABLE `COMPANY` (
	`COMPANY_PK`	VARCHAR(20)	NOT NULL,
	`COMPANY_NAME`	VARCHAR(20)	NULL
);

CREATE TABLE `CAR` (
	`CAR_ID`	VARCHAR(20)	NOT NULL,
	`COMPANY_PK`	VARCHAR(20)	NOT NULL,
	`CAR_NAME`	VARCHAR(20)	NULL,
	`CAR_YEAR`	INT	NULL
);

CREATE TABLE `CAR_OPTION` (
	`OPTION_ID`	VARCHAR(20)	NOT NULL,
	`CAR_ID`	VARCHAR(20)	NOT NULL,
	`COMPANY_PK`	VARCHAR(20)	NOT NULL,
	`OPTION_NAME`	VARCHAR(20)	NULL
);

ALTER TABLE `COMPANY` ADD CONSTRAINT `PK_COMPANY` PRIMARY KEY (
	`COMPANY_PK`
);

ALTER TABLE `CAR` ADD CONSTRAINT `PK_CAR` PRIMARY KEY (
	`CAR_ID`,
	`COMPANY_PK`
);

ALTER TABLE `CAR_OPTION` ADD CONSTRAINT `PK_CAR_OPTION` PRIMARY KEY (
	`OPTION_ID`,
	`CAR_ID`,
	`COMPANY_PK`
);

ALTER TABLE `CAR` ADD CONSTRAINT `FK_COMPANY_TO_CAR_1` FOREIGN KEY (
	`COMPANY_PK`
)
REFERENCES `COMPANY` (
	`COMPANY_PK`
);

ALTER TABLE `CAR_OPTION` ADD CONSTRAINT `FK_CAR_TO_CAR_OPTION_1` FOREIGN KEY (
	`CAR_ID`
)
REFERENCES `CAR` (
	`CAR_ID`
);

ALTER TABLE `CAR_OPTION` ADD CONSTRAINT `FK_CAR_TO_CAR_OPTION_2` FOREIGN KEY (
	`COMPANY_PK`
)
REFERENCES `CAR` (
	`COMPANY_PK`
);

