SELECT * FROM CAR;
SELECT 
	CC.COMPANY_NAME AS "회사이름",
    C.CAR_NAME AS "자동차이름",
    CI.YEAR_FK AS "연식",
    CO.O_COUNT AS "옵션 갯수"
    FROM CAR_INFO CI
		INNER JOIN COMPANY CC ON CC.COMPANY_PK = CI.COMPANY_FK
        INNER JOIN CAR C ON C.CAR_PK = CI.CAR_FK
        INNER JOIN (
			SELECT CAR_INFO_FK, COUNT(*) AS O_COUNT FROM CAR_OPTION
				GROUP BY CAR_INFO_FK
        ) CO ON CI.CAR_INFO_PK = CO.CAR_INFO_FK;