SELECT 
	N.CONTENT AS "공지내용", W.WRITER_NAME AS "작성자", V_COUNT AS "방문자 명수"
	FROM NOTICE N 
		INNER JOIN WRITER W ON W.WRITER_PK = N.WRITER_FK
        INNER JOIN (
			SELECT NOTICE_FK, COUNT(*) AS V_COUNT FROM VISITOR V
				GROUP BY NOTICE_FK
        ) V ON N.NOTICE_PK = V.NOTICE_FK;