CREATE TABLE `CAR_COMPANY` (
	`CC_PK`	VARCHAR(20)	NOT NULL,
	`CC_NAME`	VARCHAR(20)	NULL
);

CREATE TABLE `CAR_YEAR` (
	`CY_PK`	VARCHAR(20)	NOT NULL,
	`CY_YEAR`	INT	NULL
);

CREATE TABLE `CAR_NAME` (
	`CN_PK`	VARCHAR(20)	NOT NULL,
	`CN_NAME`	VARCHAR(20)	NULL
);

CREATE TABLE `CAR_INFO` (
	`CI_PK`	VARCHAR(20)	NOT NULL,
	`CN_FK`	VARCHAR(20)	NOT NULL,
	`CC_FK`	VARCHAR(20)	NOT NULL,
	`CY_FK`	VARCHAR(20)	NOT NULL
);

CREATE TABLE `CAR_OPTION` (
	`CO_PK`	VARCHAR(20)	NOT NULL,
	`CO_NAME`	VARCHAR(20)	NULL
);

CREATE TABLE `CAR_INFO_OPTION` (
	`CIO_PK`	VARCHAR(20)	NOT NULL,
	`CO_FK`	VARCHAR(20)	NOT NULL,
	`CI_FK`	VARCHAR(20)	NOT NULL
);

ALTER TABLE `CAR_COMPANY` ADD CONSTRAINT `PK_CAR_COMPANY` PRIMARY KEY (
	`CC_PK`
);

ALTER TABLE `CAR_YEAR` ADD CONSTRAINT `PK_CAR_YEAR` PRIMARY KEY (
	`CY_PK`
);

ALTER TABLE `CAR_NAME` ADD CONSTRAINT `PK_CAR_NAME` PRIMARY KEY (
	`CN_PK`
);

ALTER TABLE `CAR_INFO` ADD CONSTRAINT `PK_CAR_INFO` PRIMARY KEY (
	`CI_PK`,
	`CN_FK`,
	`CC_FK`,
	`CY_FK`
);

ALTER TABLE `CAR_OPTION` ADD CONSTRAINT `PK_CAR_OPTION` PRIMARY KEY (
	`CO_PK`
);

ALTER TABLE `CAR_INFO_OPTION` ADD CONSTRAINT `PK_CAR_INFO_OPTION` PRIMARY KEY (
	`CIO_PK`,
	`CO_FK`,
	`CI_FK`
);

ALTER TABLE `CAR_INFO` ADD CONSTRAINT `FK_CAR_NAME_TO_CAR_INFO_1` FOREIGN KEY (
	`CN_FK`
)
REFERENCES `CAR_NAME` (
	`CN_PK`
);

ALTER TABLE `CAR_INFO` ADD CONSTRAINT `FK_CAR_COMPANY_TO_CAR_INFO_1` FOREIGN KEY (
	`CC_FK`
)
REFERENCES `CAR_COMPANY` (
	`CC_PK`
);

ALTER TABLE `CAR_INFO` ADD CONSTRAINT `FK_CAR_YEAR_TO_CAR_INFO_1` FOREIGN KEY (
	`CY_FK`
)
REFERENCES `CAR_YEAR` (
	`CY_PK`
);

ALTER TABLE `CAR_INFO_OPTION` ADD CONSTRAINT `FK_CAR_OPTION_TO_CAR_INFO_OPTION_1` FOREIGN KEY (
	`CO_FK`
)
REFERENCES `CAR_OPTION` (
	`CO_PK`
);

ALTER TABLE `CAR_INFO_OPTION` ADD CONSTRAINT `FK_CAR_INFO_TO_CAR_INFO_OPTION_1` FOREIGN KEY (
	`CI_FK`
)
REFERENCES `CAR_INFO` (
	`CI_PK`
);
